use std::collections::HashMap;
use std::sync::atomic::{AtomicU64, Ordering};
use std::sync::Arc;

use base64::Engine;
use clap::Parser;
use rand::seq::SliceRandom;
use reqwest::Client;
use serde_json::Value;
use tokio::sync::Semaphore;
use tokio::time::{sleep, Duration, Instant};

// Bench prefix → OpenWhisk action path.
// Sorted longest-first so "disk-rand" matches before "disk".
const BENCH_TO_ACTION: &[(&str, &str)] = &[
    ("disk-rand", "/guest/bench_disk_rand"),
    ("disk-seq", "/guest/bench_disk_seq"),
    ("chameleon", "/guest/bench_chameleon"),
    ("float", "/guest/bench_float"),
    ("gzip", "/guest/bench_gzip"),
    ("json", "/guest/bench_json"),
    ("aes", "/guest/bench_aes"),
];

#[derive(Parser)]
#[command(name = "wasm-loadgen", about = "Trace replay engine for OpenWhisk WASM actions")]
struct Args {
    /// Path to the trace spec CSV generated by shrinkray
    #[arg(short, long)]
    trace: String,

    /// Number of minutes to replay (default: all minutes in the trace)
    #[arg(short, long)]
    minutes: Option<usize>,

    /// Max rows to keep per benchmark type (for even distribution)
    #[arg(long, default_value_t = 5)]
    max_per_bench: usize,

    /// Max concurrent in-flight HTTP requests
    #[arg(long, default_value_t = 50)]
    concurrency: usize,

    /// Accept invalid TLS certificates (common with self-hosted OpenWhisk)
    #[arg(long, default_value_t = true)]
    insecure: bool,

    /// Print the execution plan without invoking any actions
    #[arg(long)]
    dry_run: bool,
}

struct WskConfig {
    api_host: String,
    auth_header: String,
}

struct TraceRow {
    bench_type: String,
    action_path: String,
    payload: Value,
    rpm: Vec<u32>,
}

fn parse_wskprops() -> WskConfig {
    let home = std::env::var("HOME").expect("HOME not set");
    let path = format!("{home}/.wskprops");
    let content =
        std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("Failed to read {path}: {e}"));

    let mut api_host = None;
    let mut auth = None;

    for line in content.lines() {
        let line = line.trim();
        if let Some(val) = line.strip_prefix("APIHOST=") {
            api_host = Some(val.trim().to_string());
        } else if let Some(val) = line.strip_prefix("AUTH=") {
            auth = Some(val.trim().to_string());
        }
    }

    let mut api_host = api_host.expect("APIHOST not found in ~/.wskprops");
    let auth = auth.expect("AUTH not found in ~/.wskprops");
    let b64 = base64::engine::general_purpose::STANDARD.encode(&auth);

    if !api_host.starts_with("http://") && !api_host.starts_with("https://") {
        api_host = format!("https://{api_host}");
    }

    WskConfig {
        api_host: api_host.trim_end_matches('/').to_string(),
        auth_header: format!("Basic {b64}"),
    }
}

/// Maps a bench name like "gzip-ad2ebb2666f4c4877b4" to ("gzip", "/guest/bench_gzip").
fn resolve_action(bench_name: &str) -> Option<(&'static str, &'static str)> {
    for &(prefix, action) in BENCH_TO_ACTION {
        if bench_name.starts_with(prefix)
            && bench_name.as_bytes().get(prefix.len()) == Some(&b'-')
        {
            return Some((prefix, action));
        }
    }
    None
}

fn parse_trace(path: &str) -> Vec<TraceRow> {
    let mut reader = csv::ReaderBuilder::new()
        .has_headers(true)
        .flexible(true)
        .from_path(path)
        .unwrap_or_else(|e| panic!("Failed to open {path}: {e}"));

    let mut rows = Vec::new();

    for (line_no, result) in reader.records().enumerate() {
        let record = result.unwrap_or_else(|e| panic!("CSV parse error at line {}: {e}", line_no + 2));

        let wreq_json: Value = serde_json::from_str(&record[1])
            .unwrap_or_else(|e| panic!("Bad mapped_wreq JSON at line {}: {e}", line_no + 2));

        let bench = wreq_json["bench"]
            .as_str()
            .unwrap_or_else(|| panic!("Missing bench field at line {}", line_no + 2));

        let payload_str = wreq_json["payload"]
            .as_str()
            .unwrap_or_else(|| panic!("Missing payload field at line {}", line_no + 2));

        let payload: Value = serde_json::from_str(payload_str)
            .unwrap_or_else(|e| panic!("Bad payload JSON at line {}: {e}", line_no + 2));

        let (bench_type, action_path) = match resolve_action(bench) {
            Some((bt, ap)) => (bt.to_string(), ap.to_string()),
            None => {
                eprintln!("warning: unknown benchmark '{bench}', skipping");
                continue;
            }
        };

        let num_minute_cols = record.len() - 2;
        let rpm: Vec<u32> = (0..num_minute_cols)
            .map(|i| record[i + 2].parse::<u32>().unwrap_or(0))
            .collect();

        rows.push(TraceRow {
            bench_type,
            action_path,
            payload,
            rpm,
        });
    }

    rows
}

fn filter_rows(rows: Vec<TraceRow>, max_per_bench: usize) -> Vec<TraceRow> {
    let mut groups: HashMap<String, Vec<TraceRow>> = HashMap::new();
    for row in rows {
        groups.entry(row.bench_type.clone()).or_default().push(row);
    }

    let mut filtered = Vec::new();
    let mut types: Vec<_> = groups.keys().cloned().collect();
    types.sort();

    for bench_type in &types {
        let mut group = groups.remove(bench_type).unwrap();
        group.sort_by(|a, b| {
            let sum_b: u64 = b.rpm.iter().map(|&v| v as u64).sum();
            let sum_a: u64 = a.rpm.iter().map(|&v| v as u64).sum();
            sum_b.cmp(&sum_a)
        });
        let take = max_per_bench.min(group.len());
        eprintln!("  {bench_type}: {take}/{} rows", group.len());
        filtered.extend(group.into_iter().take(take));
    }

    filtered
}

/// Build the invocation URL from api_host and an action path like "/guest/bench_gzip".
fn invocation_url(api_host: &str, action_path: &str) -> String {
    let trimmed = action_path.trim_start_matches('/');
    let (namespace, action) = trimmed
        .split_once('/')
        .unwrap_or_else(|| panic!("Bad action path: {action_path}"));
    format!("{api_host}/api/v1/namespaces/{namespace}/actions/{action}")
}

fn print_plan(rows: &[TraceRow], minutes_to_run: usize) {
    let mut grand_total: u64 = 0;

    for minute in 0..minutes_to_run {
        let mut counts: HashMap<&str, u64> = HashMap::new();
        for row in rows {
            let n = *row.rpm.get(minute).unwrap_or(&0) as u64;
            *counts.entry(&row.bench_type).or_default() += n;
        }
        let total: u64 = counts.values().sum();
        grand_total += total;

        let mut parts: Vec<_> = counts.into_iter().collect();
        parts.sort_by_key(|(name, _)| *name);
        let breakdown: Vec<String> = parts
            .iter()
            .map(|(name, count)| format!("{name}={count}"))
            .collect();

        eprintln!(
            "  minute {:>2}: {:>5} total  [{}]",
            minute + 1,
            total,
            breakdown.join(", ")
        );
    }
    eprintln!("  grand total: {grand_total} invocations across {minutes_to_run} minutes");
}

struct Invocation {
    action_path: String,
    payload: Value,
}

#[tokio::main]
async fn main() {
    let args = Args::parse();

    let config = parse_wskprops();
    eprintln!("OpenWhisk API: {}", config.api_host);

    eprintln!("Loading trace: {}", args.trace);
    let rows = parse_trace(&args.trace);
    let total_minutes = rows.first().map(|r| r.rpm.len()).unwrap_or(0);
    eprintln!("Parsed {} rows, {} minute columns\n", rows.len(), total_minutes);

    eprintln!("Filtering (max {} per bench type):", args.max_per_bench);
    let rows = filter_rows(rows, args.max_per_bench);
    eprintln!("  total: {} rows\n", rows.len());

    let minutes_to_run = args.minutes.unwrap_or(total_minutes).min(total_minutes);

    eprintln!("Execution plan ({minutes_to_run} minutes):");
    print_plan(&rows, minutes_to_run);
    eprintln!();

    if args.dry_run {
        eprintln!("Dry run — exiting without invoking actions.");
        return;
    }

    let client = Client::builder()
        .danger_accept_invalid_certs(args.insecure)
        .pool_max_idle_per_host(args.concurrency)
        .build()
        .expect("Failed to create HTTP client");

    let semaphore = Arc::new(Semaphore::new(args.concurrency));
    let total_ok = Arc::new(AtomicU64::new(0));
    let total_err = Arc::new(AtomicU64::new(0));

    let experiment_start = Instant::now();

    for minute in 0..minutes_to_run {
        let minute_start = Instant::now();

        let mut invocations: Vec<Invocation> = Vec::new();
        for row in &rows {
            let count = *row.rpm.get(minute).unwrap_or(&0);
            for _ in 0..count {
                invocations.push(Invocation {
                    action_path: row.action_path.clone(),
                    payload: row.payload.clone(),
                });
            }
        }

        let n = invocations.len();
        if n == 0 {
            eprintln!("[minute {:>2}] no invocations, sleeping 60s", minute + 1);
            sleep(Duration::from_secs(60)).await;
            continue;
        }

        invocations.shuffle(&mut rand::thread_rng());

        eprintln!(
            "[minute {:>2}] dispatching {} invocations ({:.1} rps)",
            minute + 1,
            n,
            n as f64 / 60.0,
        );

        for (i, inv) in invocations.into_iter().enumerate() {
            let target = minute_start + Duration::from_secs_f64(60.0 * i as f64 / n as f64);
            let now = Instant::now();
            if target > now {
                sleep(target - now).await;
            }

            let client = client.clone();
            let auth = config.auth_header.clone();
            let host = config.api_host.clone();
            let sem = semaphore.clone();
            let ok = total_ok.clone();
            let err = total_err.clone();

            tokio::spawn(async move {
                let _permit = sem.acquire().await.unwrap();
                let url = invocation_url(&host, &inv.action_path);

                let result = client
                    .post(&url)
                    .header("Authorization", &auth)
                    .json(&inv.payload)
                    .send()
                    .await;

                match result {
                    Ok(resp) if resp.status().is_success() || resp.status().as_u16() == 202 => {
                        ok.fetch_add(1, Ordering::Relaxed);
                    }
                    Ok(resp) => {
                        let status = resp.status();
                        let body = resp.text().await.unwrap_or_default();
                        eprintln!("  WARN {}: {} — {}", inv.action_path, status, body);
                        err.fetch_add(1, Ordering::Relaxed);
                    }
                    Err(e) => {
                        eprintln!("  ERROR {}: {e}", inv.action_path);
                        err.fetch_add(1, Ordering::Relaxed);
                    }
                }
            });
        }

        // Wait for the remainder of the minute
        let elapsed = minute_start.elapsed();
        if elapsed < Duration::from_secs(60) {
            sleep(Duration::from_secs(60) - elapsed).await;
        }

        eprintln!(
            "  ok={}, err={}",
            total_ok.load(Ordering::Relaxed),
            total_err.load(Ordering::Relaxed),
        );
    }

    // Give in-flight requests a few seconds to finish
    eprintln!("\nDraining in-flight requests...");
    sleep(Duration::from_secs(5)).await;

    let elapsed = experiment_start.elapsed();
    eprintln!("\n=== Done ===");
    eprintln!("Duration:  {:.1}s", elapsed.as_secs_f64());
    eprintln!("Succeeded: {}", total_ok.load(Ordering::Relaxed));
    eprintln!("Failed:    {}", total_err.load(Ordering::Relaxed));
}
