use std::collections::HashMap;
use std::io::{BufWriter, Write};
use std::sync::atomic::{AtomicU64, Ordering};
use std::sync::Arc;
use std::time::{Duration, SystemTime, UNIX_EPOCH};

use base64::Engine;
use clap::Parser;
use rand::seq::SliceRandom;
use reqwest::Client;
use serde::{Deserialize, Serialize};
use serde_json::Value;
use tokio::sync::{Mutex, Semaphore};
use tokio::time::{sleep, Instant};

// Bench prefix → OpenWhisk action name.
// Sorted longest-first so "disk-rand" matches before "disk".
const BENCH_TO_ACTION: &[(&str, &str)] = &[
    ("disk-rand", "bench_disk_rand"),
    ("disk-seq",  "bench_disk_seq"),
    ("chameleon", "bench_chameleon"),
    ("float",     "bench_float"),
    ("gzip",      "bench_gzip"),
    ("json",      "bench_json"),
    ("aes",       "bench_aes"),
];

// ── CLI ───────────────────────────────────────────────────────────────────────

#[derive(Parser)]
#[command(name = "ow-loadgen", about = "Trace-replay load generator for OpenWhisk")]
struct Args {
    /// Path to the trace spec CSV generated by shrinkray
    #[arg(short, long)]
    trace: String,

    /// Path to the output NDJSON file for per-invocation results
    #[arg(short, long)]
    outfile: String,

    /// Number of minutes to replay (default: all minutes in the trace)
    #[arg(short, long)]
    minutes: Option<usize>,

    /// Max rows to keep per benchmark type (highest-RPM rows are kept)
    #[arg(long, default_value_t = 5)]
    max_per_bench: usize,

    /// Max concurrent in-flight HTTP requests
    #[arg(long, default_value_t = 50)]
    concurrency: usize,

    /// OpenWhisk host (overrides ~/.wskprops APIHOST)
    #[arg(long)]
    ow_host: Option<String>,

    /// OpenWhisk auth in "user:password" format (overrides ~/.wskprops AUTH)
    #[arg(long)]
    auth: Option<String>,

    /// OpenWhisk namespace
    #[arg(long, default_value = "guest")]
    namespace: String,

    /// Use OpenWhisk blocking mode (latency includes full execution time)
    #[arg(long)]
    blocking: bool,

    /// Accept invalid TLS certificates (common with self-hosted OpenWhisk)
    #[arg(long, default_value_t = true)]
    insecure: bool,

    /// Print the execution plan without invoking any actions
    #[arg(long)]
    dry_run: bool,
}

// ── Config & data structures ──────────────────────────────────────────────────

struct WskConfig {
    api_host: String,
    auth_header: String,
}

struct TraceRow {
    bench_type: String,
    action_name: String,
    payload: Value,
    rpm: Vec<u32>,
}

struct Invocation {
    bench_type: String,
    action_name: String,
    payload: Value,
    minute: usize,
}

/// One line written to the NDJSON output file.
#[derive(Serialize, Deserialize)]
struct InvocationRecord {
    bench: String,
    minute: usize,
    /// Unix timestamp (µs) when the HTTP request was dispatched.
    issued_at_us: u64,
    /// Round-trip HTTP latency in µs.
    latency_us: u64,
    /// HTTP status code returned by OpenWhisk.
    status_code: u16,
    /// OpenWhisk activation ID, present on successful dispatches.
    activation_id: Option<String>,
}

// ── Auth / config ─────────────────────────────────────────────────────────────

fn parse_wskprops() -> WskConfig {
    let home = std::env::var("HOME").expect("HOME not set");
    let path = format!("{home}/.wskprops");
    let content =
        std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("Failed to read {path}: {e}"));

    let mut api_host = None;
    let mut auth = None;

    for line in content.lines() {
        let line = line.trim();
        if let Some(val) = line.strip_prefix("APIHOST=") {
            api_host = Some(val.trim().to_string());
        } else if let Some(val) = line.strip_prefix("AUTH=") {
            auth = Some(val.trim().to_string());
        }
    }

    let mut api_host = api_host.expect("APIHOST not found in ~/.wskprops");
    let auth = auth.expect("AUTH not found in ~/.wskprops");

    if !api_host.starts_with("http://") && !api_host.starts_with("https://") {
        api_host = format!("https://{api_host}");
    }

    make_config(api_host.trim_end_matches('/').to_string(), &auth)
}

fn make_config(api_host: String, auth: &str) -> WskConfig {
    let b64 = base64::engine::general_purpose::STANDARD.encode(auth);
    WskConfig {
        api_host,
        auth_header: format!("Basic {b64}"),
    }
}

// ── CSV parsing ───────────────────────────────────────────────────────────────

fn resolve_action(bench_name: &str) -> Option<(&'static str, &'static str)> {
    for &(prefix, action) in BENCH_TO_ACTION {
        if bench_name.starts_with(prefix)
            && bench_name.as_bytes().get(prefix.len()) == Some(&b'-')
        {
            return Some((prefix, action));
        }
    }
    None
}

fn parse_trace(path: &str) -> Vec<TraceRow> {
    let mut reader = csv::ReaderBuilder::new()
        .has_headers(true)
        .flexible(true)
        .from_path(path)
        .unwrap_or_else(|e| panic!("Failed to open {path}: {e}"));

    let mut rows = Vec::new();

    for (line_no, result) in reader.records().enumerate() {
        let record =
            result.unwrap_or_else(|e| panic!("CSV parse error at line {}: {e}", line_no + 2));

        let wreq_json: Value = serde_json::from_str(&record[1])
            .unwrap_or_else(|e| panic!("Bad mapped_wreq JSON at line {}: {e}", line_no + 2));

        let bench = wreq_json["bench"]
            .as_str()
            .unwrap_or_else(|| panic!("Missing bench field at line {}", line_no + 2));

        let payload_str = wreq_json["payload"]
            .as_str()
            .unwrap_or_else(|| panic!("Missing payload field at line {}", line_no + 2));

        let payload: Value = serde_json::from_str(payload_str)
            .unwrap_or_else(|e| panic!("Bad payload JSON at line {}: {e}", line_no + 2));

        let (bench_type, action_name) = match resolve_action(bench) {
            Some((bt, an)) => (bt.to_string(), an.to_string()),
            None => {
                eprintln!("warning: unknown benchmark '{bench}', skipping");
                continue;
            }
        };

        let num_minute_cols = record.len() - 2;
        let rpm: Vec<u32> = (0..num_minute_cols)
            .map(|i| record[i + 2].parse::<u32>().unwrap_or(0))
            .collect();

        rows.push(TraceRow { bench_type, action_name, payload, rpm });
    }

    rows
}

// ── Row filtering ─────────────────────────────────────────────────────────────

fn filter_rows(rows: Vec<TraceRow>, max_per_bench: usize) -> Vec<TraceRow> {
    let mut groups: HashMap<String, Vec<TraceRow>> = HashMap::new();
    for row in rows {
        groups.entry(row.bench_type.clone()).or_default().push(row);
    }

    let mut filtered = Vec::new();
    let mut types: Vec<_> = groups.keys().cloned().collect();
    types.sort();

    for bench_type in &types {
        let mut group = groups.remove(bench_type).unwrap();
        group.sort_by(|a, b| {
            let sum_b: u64 = b.rpm.iter().map(|&v| v as u64).sum();
            let sum_a: u64 = a.rpm.iter().map(|&v| v as u64).sum();
            sum_b.cmp(&sum_a)
        });
        let take = max_per_bench.min(group.len());
        eprintln!("  {bench_type}: {take}/{} rows", group.len());
        filtered.extend(group.into_iter().take(take));
    }

    filtered
}

// ── Plan printing ─────────────────────────────────────────────────────────────

fn print_plan(rows: &[TraceRow], minutes_to_run: usize) {
    let mut grand_total: u64 = 0;

    for minute in 0..minutes_to_run {
        let mut counts: HashMap<&str, u64> = HashMap::new();
        for row in rows {
            let n = *row.rpm.get(minute).unwrap_or(&0) as u64;
            *counts.entry(&row.bench_type).or_default() += n;
        }
        let total: u64 = counts.values().sum();
        grand_total += total;

        let mut parts: Vec<_> = counts.into_iter().collect();
        parts.sort_by_key(|(name, _)| *name);
        let breakdown: Vec<String> =
            parts.iter().map(|(name, count)| format!("{name}={count}")).collect();

        eprintln!(
            "  minute {:>2}: {:>5} total  [{}]",
            minute + 1,
            total,
            breakdown.join(", ")
        );
    }
    eprintln!("  grand total: {grand_total} invocations across {minutes_to_run} minutes");
}

// ── Entry point ───────────────────────────────────────────────────────────────

#[tokio::main]
async fn main() {
    let args = Args::parse();

    // CLI flags override ~/.wskprops
    let config = match (&args.ow_host, &args.auth) {
        (Some(host), Some(auth)) => {
            let mut host = host.clone();
            if !host.starts_with("http://") && !host.starts_with("https://") {
                host = format!("https://{host}");
            }
            make_config(host.trim_end_matches('/').to_string(), auth)
        }
        _ => parse_wskprops(),
    };

    eprintln!("OpenWhisk API: {}", config.api_host);
    eprintln!("Namespace:     {}", args.namespace);
    eprintln!("Blocking:      {}", args.blocking);
    eprintln!("Output:        {}", args.outfile);
    eprintln!("Loading trace: {}", args.trace);

    let rows = parse_trace(&args.trace);
    let total_minutes = rows.first().map(|r| r.rpm.len()).unwrap_or(0);
    eprintln!("Parsed {} rows, {} minute columns\n", rows.len(), total_minutes);

    eprintln!("Filtering (max {} per bench type):", args.max_per_bench);
    let rows = filter_rows(rows, args.max_per_bench);
    eprintln!("  total: {} rows\n", rows.len());

    let minutes_to_run = args.minutes.unwrap_or(total_minutes).min(total_minutes);

    eprintln!("Execution plan ({minutes_to_run} minutes):");
    print_plan(&rows, minutes_to_run);
    eprintln!();

    if args.dry_run {
        eprintln!("Dry run — exiting without invoking actions.");
        return;
    }

    // Open output file
    let outfile = std::fs::OpenOptions::new()
        .create(true)
        .truncate(true)
        .write(true)
        .open(&args.outfile)
        .unwrap_or_else(|e| panic!("Failed to open output file {}: {e}", args.outfile));
    let writer = Arc::new(Mutex::new(BufWriter::new(outfile)));

    let client = Client::builder()
        .danger_accept_invalid_certs(args.insecure)
        .pool_max_idle_per_host(args.concurrency)
        .build()
        .expect("Failed to create HTTP client");

    let semaphore = Arc::new(Semaphore::new(args.concurrency));
    let total_ok  = Arc::new(AtomicU64::new(0));
    let total_err = Arc::new(AtomicU64::new(0));

    // Ctrl-C: finish the current minute then exit cleanly
    let shutdown = Arc::new(tokio::sync::Notify::new());
    {
        let shutdown = shutdown.clone();
        tokio::spawn(async move {
            tokio::signal::ctrl_c().await.ok();
            eprintln!("\nCtrl-C — finishing current minute then draining...");
            shutdown.notify_waiters();
        });
    }

    let experiment_start = Instant::now();

    'minutes: for minute in 0..minutes_to_run {
        let minute_start    = Instant::now();
        let minute_deadline = minute_start + Duration::from_secs(60);

        // Collect all invocations for this minute across all rows
        let mut invocations: Vec<Invocation> = Vec::new();
        for row in &rows {
            let count = *row.rpm.get(minute).unwrap_or(&0);
            for _ in 0..count {
                invocations.push(Invocation {
                    bench_type:  row.bench_type.clone(),
                    action_name: row.action_name.clone(),
                    payload:     row.payload.clone(),
                    minute:      minute + 1,
                });
            }
        }

        let n = invocations.len();
        if n == 0 {
            eprintln!("[minute {:>2}] no invocations, sleeping 60s", minute + 1);
            tokio::select! {
                _ = sleep(Duration::from_secs(60)) => {}
                _ = shutdown.notified() => break 'minutes,
            }
            continue;
        }

        // Shuffle so bench types are interleaved throughout the minute
        invocations.shuffle(&mut rand::thread_rng());

        eprintln!(
            "[minute {:>2}] dispatching {} invocations ({:.1} rps)",
            minute + 1,
            n,
            n as f64 / 60.0,
        );

        for (i, inv) in invocations.into_iter().enumerate() {
            // Equidistant spacing across the 60-second window
            let target = minute_start + Duration::from_secs_f64(60.0 * i as f64 / n as f64);
            let now = Instant::now();
            if target > now {
                tokio::select! {
                    _ = sleep(target - now) => {}
                    _ = shutdown.notified() => break 'minutes,
                }
            }

            let client   = client.clone();
            let auth     = config.auth_header.clone();
            let url      = format!(
                "{}/api/v1/namespaces/{}/actions/{}?blocking={}&result=false",
                config.api_host, args.namespace, inv.action_name, args.blocking,
            );
            let sem      = semaphore.clone();
            let ok       = total_ok.clone();
            let err      = total_err.clone();
            let writer   = writer.clone();
            // Bound each request to the remaining time in this minute (min 1s)
            let timeout  = minute_deadline
                .saturating_duration_since(Instant::now())
                .max(Duration::from_secs(1));

            tokio::spawn(async move {
                let _permit = sem.acquire().await.unwrap();

                let issued_at_us = SystemTime::now()
                    .duration_since(UNIX_EPOCH)
                    .unwrap_or_default()
                    .as_micros() as u64;

                let t_start = Instant::now();
                let result  = client
                    .post(&url)
                    .header("Authorization", &auth)
                    .timeout(timeout)
                    .json(&inv.payload)
                    .send()
                    .await;
                let latency_us = t_start.elapsed().as_micros() as u64;

                match result {
                    Ok(resp) => {
                        let status_code = resp.status().as_u16();
                        // Parse body for activation ID (best-effort)
                        let body = resp.json::<Value>().await.unwrap_or_default();
                        let activation_id =
                            body["activationId"].as_str().map(str::to_owned);

                        if status_code < 300 || status_code == 202 {
                            ok.fetch_add(1, Ordering::Relaxed);
                        } else {
                            eprintln!(
                                "  WARN {}: HTTP {status_code} — {}",
                                inv.action_name,
                                body.to_string()
                            );
                            err.fetch_add(1, Ordering::Relaxed);
                        }

                        let record = InvocationRecord {
                            bench: inv.bench_type,
                            minute: inv.minute,
                            issued_at_us,
                            latency_us,
                            status_code,
                            activation_id,
                        };
                        if let Ok(mut line) = serde_json::to_string(&record) {
                            line.push('\n');
                            let mut w = writer.lock().await;
                            let _ = w.write_all(line.as_bytes());
                        }
                    }
                    Err(e) => {
                        eprintln!("  ERROR {}: {e}", inv.action_name);
                        err.fetch_add(1, Ordering::Relaxed);
                    }
                }
            });
        }

        // Wait for the remainder of the minute
        let elapsed = minute_start.elapsed();
        if elapsed < Duration::from_secs(60) {
            tokio::select! {
                _ = sleep(Duration::from_secs(60) - elapsed) => {}
                _ = shutdown.notified() => break 'minutes,
            }
        }

        eprintln!(
            "  ok={}, err={}",
            total_ok.load(Ordering::Relaxed),
            total_err.load(Ordering::Relaxed),
        );
    }

    // Give in-flight requests a few seconds to land
    eprintln!("\nDraining in-flight requests...");
    sleep(Duration::from_secs(5)).await;

    // Flush the output file
    {
        let mut w = writer.lock().await;
        let _ = w.flush();
    }

    let elapsed = experiment_start.elapsed();
    eprintln!("\n=== Done ===");
    eprintln!("Duration:  {:.1}s", elapsed.as_secs_f64());
    eprintln!("Output:    {}", args.outfile);
    eprintln!("Succeeded: {}", total_ok.load(Ordering::Relaxed));
    eprintln!("Failed:    {}", total_err.load(Ordering::Relaxed));
}